analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - use_super_parameters
    - sort_child_properties_last
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_declarations
    - require_trailing_commas
