/**
 * Builds the app's web payload.
 *
 *   node scripts/build-www.mjs
 *
 *   public/demo/void-striker/   →   mobile/void-striker/www/
 *   src/native.js               →   mobile/void-striker/www/native.js
 *
 * The source is deliberately the site's demo build rather than
 * game/void_striker.html itself. The game's one external dependency is an
 * `@import` of two faces from Google Fonts, and `npm run demo` at the repo root
 * already downloads them and rewrites that import to local files. Repeating
 * that here would be a second implementation of the same thing, drifting from
 * the first.
 *
 * It also means the packaged app and the playable demo on the website are
 * byte-for-byte the same game, which is worth having: when a player reports
 * something, there is one build to reproduce it in.
 *
 * A packaged app that reaches the network to render its own text is worse than
 * a web page doing it — an app store reviewer reasonably asks why a game with
 * no account and no server is contacting Google, the privacy policy says it
 * contacts nobody, and the app would render in fallback fonts on a plane. So
 * this script does not merely assume the demo build is self-contained: it
 * checks, and refuses to build if it is not.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = fileURLToPath(new URL('..', import.meta.url));
const REPO = fileURLToPath(new URL('../../../', import.meta.url));
const SRC_DIR = join(REPO, 'public', 'demo', 'void-striker');
const OUT_DIR = join(HERE, 'www');

if (!existsSync(join(SRC_DIR, 'index.html'))) {
  console.error(
    'Missing public/demo/void-striker/index.html.\n' +
      'Run `npm run demo` at the repo root first — it builds the game with its\n' +
      'fonts self-hosted, which is what this script packages.',
  );
  process.exit(1);
}

let html = readFileSync(join(SRC_DIR, 'index.html'), 'utf8');

/**
 * Nothing may point off-device.
 *
 * Checked against the built file rather than trusted, because the failure is
 * silent: a build with a live @import still looks perfect on the developer's
 * desk, on wifi, in a city.
 */
const remote = [...html.matchAll(/\b(?:src|href)\s*=\s*["'](https?:\/\/[^"']+)/gi), ...html.matchAll(/url\(\s*["']?(https?:\/\/[^)"']+)/gi)]
  .map((m) => m[1]);

if (remote.length) {
  console.error(
    'The demo build still references remote resources:\n' +
      remote.map((u) => `  ${u}`).join('\n') +
      '\n\nA packaged app must not fetch anything at runtime. Re-run `npm run demo`\n' +
      'at the repo root, which self-hosts them.',
  );
  process.exit(1);
}

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });
cpSync(SRC_DIR, OUT_DIR, { recursive: true });

/**
 * Load the shim before the game.
 *
 * It wraps the AudioContext constructor, so it has to be in place before the
 * game's script runs — the game creates its context on the first touch, but
 * "first touch" is not something to bet the ordering on.
 */
const tag = '<script src="native.js"></script>';
if (!html.includes('</head>')) {
  console.error('No </head> in the game HTML — cannot inject the native shim.');
  process.exit(1);
}
html = html.replace('</head>', `${tag}\n</head>`);

const banner =
  '<!--\n' +
  '  Generated by mobile/void-striker/scripts/build-www.mjs. Do not edit.\n' +
  '  The game lives at game/void_striker.html; run `npm run demo` at the repo\n' +
  '  root and then `npm run sync` here.\n' +
  '-->\n';

writeFileSync(join(OUT_DIR, 'index.html'), banner + html);
cpSync(join(HERE, 'src', 'native.js'), join(OUT_DIR, 'native.js'));

console.log(`  www/  built from public/demo/void-striker (${remote.length} remote references)`);
