/**
 * Builds the playable demo from the game's source.
 *
 *   node scripts/install-demo.mjs
 *
 *   game/void_striker.html   →   public/demo/void-striker/index.html
 *                            +   public/demo/void-striker/fonts/*.woff2
 *
 * The game is a single self-contained file with exactly one external
 * dependency: an `@import` of Orbitron and Share Tech Mono from Google Fonts.
 * This script downloads those faces, writes them next to the game, and rewrites
 * the import to point at the local copies.
 *
 * That matters for three reasons, in order of importance:
 *
 *   1. Privacy. A Google Fonts request hands the visitor's IP address and
 *      user-agent to a third party on every page view. This site publishes a
 *      privacy policy that says we keep collection minimal, and an embedded
 *      demo quietly calling out to Google would make that statement false.
 *   2. Reliability. The demo is the studio's one piece of proof that it ships
 *      working software. It should not fail to render correctly because a
 *      font CDN is slow, blocked, or down.
 *   3. Consistency. Every other face on this site is self-hosted already.
 *
 * It is a script rather than a one-time hand edit because the game is under
 * active development: dropping in a new build should be one command, not a
 * manual re-edit that is forgotten and silently lost.
 *
 * The game's own source is never modified — game/void_striker.html stays
 * exactly as authored, and everything here happens to the copy.
 */

import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'game', 'void_striker.html');
const OUT_DIR = join(ROOT, 'public', 'demo', 'void-striker');
const FONT_DIR = join(OUT_DIR, 'fonts');

/** A modern desktop UA, so the CSS we get back is woff2 rather than ttf. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const html = readFileSync(SRC, 'utf8');

// The one line we need to replace. Captured rather than hardcoded so that a
// new build which changes the weights or adds a family still works.
const importRe = /@import\s+url\(['"](https:\/\/fonts\.googleapis\.com\/[^'"]+)['"]\);?/;
const match = html.match(importRe);

if (!match) {
  // Not an error: a future build may already have no external fonts.
  console.log('  no Google Fonts import found — copying the game unchanged');
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'index.html'), html);
  process.exit(0);
}

console.log(`  fetching ${match[1]}`);
const cssRes = await fetch(match[1], { headers: { 'user-agent': UA } });
if (!cssRes.ok) throw new Error(`Google Fonts returned ${cssRes.status}`);
let css = await cssRes.text();

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(FONT_DIR, { recursive: true });

// Rewrite every remote face URL to a local file, downloading as we go. The
// same face can appear under several unicode-ranges, so the cache keeps us
// from fetching one file five times.
const seen = new Map();
const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]);

for (const url of urls) {
  if (seen.has(url)) continue;
  // e.g. .../s/orbitron/v31/yMJRMIlzdpvBhQQL_Qq7dy0.woff2 → orbitron-v31-…woff2
  const parts = url.split('/');
  const name = `${parts[parts.length - 3]}-${parts[parts.length - 1]}`.replace(/[^\w.-]/g, '_');
  const res = await fetch(url, { headers: { 'user-agent': UA } });
  if (!res.ok) throw new Error(`font fetch failed (${res.status}): ${url}`);
  writeFileSync(join(FONT_DIR, name), Buffer.from(await res.arrayBuffer()));
  seen.set(url, `fonts/${name}`);
  console.log(`    ${name}`);
}

for (const [remote, local] of seen) css = css.split(remote).join(local);

const banner =
  '/* Fonts self-hosted by scripts/install-demo.mjs — do not edit this file.\n' +
  '   Edit game/void_striker.html and re-run `npm run demo`. */\n';

const out = html.replace(importRe, banner + css.trim());
writeFileSync(join(OUT_DIR, 'index.html'), out);

console.log(`\n  public/demo/void-striker/index.html  (${seen.size} faces self-hosted)`);
